#!/usr/bin/env bash

# target-runner for IRACE -> EMILI with ILS on PFSP_MS
# Called by irace as:
#   target-runner configID instanceID seed instance --initial X --neigh Y --tmax Z

config_id="$1"
instance_id="$2"
seed="$3"
instance="$4"
shift 4

# Default values (au cas où)
initial="random"
neigh="transpose"
tmax=30

# Parse parameters passed by irace
while [[ $# -gt 0 ]]
do
    case "$1" in
        --initial) initial="$2"; shift 2 ;;
        --neigh)   neigh="$2";   shift 2 ;;
        --tmax)    tmax="$2";    shift 2 ;;
        *)         shift ;;
    esac
done

# Commande EMILI :
# ../../build/emili <instance> PFSP_MS ils first <initial> locmin <neigh> locmin testper improve -it <tmax>

../../build/emili "$instance" PFSP_MS \
    ils first "$initial" locmin "$neigh" locmin testper improve -it "$tmax" \
    > emili_out.txt 2>&1

# Extraire la valeur de la fonction objectif
# On suppose une ligne du style: "Objective function value: 12345"
value=$(grep -i "Objective function value" emili_out.txt | awk '{print $NF}' | tail -n 1)

# Si on ne trouve rien -> gros coût (pénalité)
if [[ -z "$value" ]] || ! [[ "$value" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
    value=1e12
fi

# irace MINIMISE cette valeur
echo "$value"
